-- ==========================================
-- MERCADO SOCIAL - TABLAS ADICIONALES (SAFE)
-- ==========================================
-- Script SEGURO: No falla si ya existe
-- Ejecutar en: Supabase SQL Editor

-- ==========================================
-- 1. TABLA OPINIONS (si no existe)
-- ==========================================
CREATE TABLE IF NOT EXISTS opinions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_name TEXT NOT NULL DEFAULT 'Anónimo',
    content TEXT NOT NULL,
    value NUMERIC NOT NULL,
    currency TEXT NOT NULL DEFAULT 'USD',
    sentiment TEXT CHECK (sentiment IN ('positive', 'neutral', 'negative')) DEFAULT 'neutral',
    created_at TIMESTAMPTZ DEFAULT now(),
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE
);

-- Realtime (ignorar si ya existe)
DO $$ 
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE opinions;
EXCEPTION WHEN duplicate_object THEN
    RAISE NOTICE 'opinions ya está en supabase_realtime, ignorando...';
END $$;

-- RLS (solo si no existe)
ALTER TABLE opinions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read Opinions" ON opinions;
DROP POLICY IF EXISTS "Public Insert Opinions" ON opinions;
CREATE POLICY "Public Read Opinions" ON opinions FOR SELECT USING (true);
CREATE POLICY "Public Insert Opinions" ON opinions FOR INSERT WITH CHECK (true);

-- ==========================================
-- 2. TABLA PRICE_HISTORY (si no existe)
-- ==========================================
CREATE TABLE IF NOT EXISTS price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    price NUMERIC NOT NULL,
    currency TEXT NOT NULL DEFAULT 'USD',
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Realtime (ignorar si ya existe)
DO $$ 
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE price_history;
EXCEPTION WHEN duplicate_object THEN
    RAISE NOTICE 'price_history ya está en supabase_realtime, ignorando...';
END $$;

-- RLS
ALTER TABLE price_history ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read Price History" ON price_history;
DROP POLICY IF EXISTS "Public Insert Price History" ON price_history;
CREATE POLICY "Public Read Price History" ON price_history FOR SELECT USING (true);
CREATE POLICY "Public Insert Price History" ON price_history FOR INSERT WITH CHECK (true);

-- Índice para queries rápidas
CREATE INDEX IF NOT EXISTS idx_price_history_product_date 
ON price_history (product_id, created_at DESC);

-- ==========================================
-- 3. DATOS DE EJEMPLO (solo si tablas vacías)
-- ==========================================

-- Opinions (solo si está vacía)
INSERT INTO opinions (product_id, author_name, content, value, currency, sentiment, created_at)
SELECT * FROM (VALUES
    (1::BIGINT, 'TechReviewer', 'La consultoría estratégica en AI es clave este año.', 5500::NUMERIC, 'USD', 'positive', now() - interval '3 days'),
    (1, 'MarketAnalyst', 'Buen precio base considerando el mercado actual.', 4800, 'USD', 'neutral', now() - interval '2 days'),
    (1, 'InnovationHub', 'El expertis de Tech Master justifica el premium.', 5100, 'USD', 'positive', now() - interval '1 day'),
    (1, 'StartupFounder', 'He visto servicios similares por mucho más.', 5250, 'USD', 'positive', now() - interval '12 hours'),
    (1, 'DataScientist', 'Precio justo para una implementación rápida.', 4950, 'USD', 'neutral', now() - interval '6 hours')
) AS v(product_id, author_name, content, value, currency, sentiment, created_at)
WHERE NOT EXISTS (SELECT 1 FROM opinions LIMIT 1);

-- Price History (solo si está vacía)
INSERT INTO price_history (product_id, price, currency, created_at)
SELECT * FROM (VALUES
    (1::BIGINT, 800::NUMERIC, 'USD', now() - interval '7 days'),
    (1, 850, 'USD', now() - interval '6 days'),
    (1, 900, 'USD', now() - interval '5 days'),
    (1, 950, 'USD', now() - interval '4 days'),
    (1, 920, 'USD', now() - interval '3 days'),
    (1, 980, 'USD', now() - interval '2 days'),
    (1, 1000, 'USD', now() - interval '1 day'),
    (1, 1000, 'USD', now())
) AS v(product_id, price, currency, created_at)
WHERE NOT EXISTS (SELECT 1 FROM price_history LIMIT 1);

-- ==========================================
-- ✅ LISTO! Script ejecutado correctamente
-- ==========================================
SELECT 'Script ejecutado correctamente!' AS resultado,
       (SELECT COUNT(*) FROM opinions) AS opiniones,
       (SELECT COUNT(*) FROM price_history) AS historial_precios;
