-- ═══════════════════════════════════════════════════════════════════════════════
-- MERCADO SOCIAL - SCRIPT SQL COMPLETO Y SEGURO
-- ═══════════════════════════════════════════════════════════════════════════════
-- Autor: Mercado Social Team
-- Fecha: 2026-01-25
-- Versión: 1.0 FULL
-- 
-- INSTRUCCIONES:
-- 1. Copiar TODO este archivo
-- 2. Pegar en Supabase SQL Editor
-- 3. Click en "Run CTRL+Enter"
-- 4. ¡Listo!
--
-- NOTA: Este script es IDEMPOTENTE - puede ejecutarse múltiples veces sin problemas
-- ═══════════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════════
-- PARTE 1: TABLAS BASE (SELLERS, PRODUCTS, VOTES, OFFERS)
-- ═══════════════════════════════════════════════════════════════════════════════

-- 1.1 TABLA: VENDEDORES (SELLERS)
CREATE TABLE IF NOT EXISTS sellers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    avatar TEXT DEFAULT 'https://api.dicebear.com/7.x/avataaars/svg?seed=Default',
    level TEXT DEFAULT 'NIVEL ESTÁNDAR',
    verified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 1.2 TABLA: PRODUCTOS (PRODUCTS)
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    owner_price NUMERIC NOT NULL,
    owner_currency TEXT NOT NULL DEFAULT 'USD',
    status TEXT CHECK (status IN ('open', 'locked', 'sold')) DEFAULT 'open',
    final_price NUMERIC,
    final_currency TEXT,
    images TEXT[] DEFAULT '{}',
    video_url TEXT,
    seller_id UUID REFERENCES sellers(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 1.3 TABLA: VOTOS (VOTES)
CREATE TABLE IF NOT EXISTS votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value NUMERIC NOT NULL,
    currency TEXT NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT now(),
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE
);

-- 1.4 TABLA: OFERTAS (OFFERS)
CREATE TABLE IF NOT EXISTS offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bidder_name TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    currency TEXT NOT NULL,
    status TEXT CHECK (status IN ('pending', 'accepted', 'rejected')) DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT now(),
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE
);


-- ═══════════════════════════════════════════════════════════════════════════════
-- PARTE 2: TABLAS ADICIONALES (OPINIONS, PRICE_HISTORY)
-- ═══════════════════════════════════════════════════════════════════════════════

-- 2.1 TABLA: OPINIONES (OPINIONS)
CREATE TABLE IF NOT EXISTS opinions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_name TEXT NOT NULL DEFAULT 'Anónimo',
    content TEXT NOT NULL,
    value NUMERIC NOT NULL,
    currency TEXT NOT NULL DEFAULT 'USD',
    sentiment TEXT CHECK (sentiment IN ('positive', 'neutral', 'negative')) DEFAULT 'neutral',
    created_at TIMESTAMPTZ DEFAULT now(),
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE
);

-- 2.2 TABLA: HISTORIAL DE PRECIOS (PRICE_HISTORY)
CREATE TABLE IF NOT EXISTS price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    price NUMERIC NOT NULL,
    currency TEXT NOT NULL DEFAULT 'USD',
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2.3 ÍNDICE PARA PRICE_HISTORY (mejora performance)
CREATE INDEX IF NOT EXISTS idx_price_history_product_date 
ON price_history (product_id, created_at DESC);


-- ═══════════════════════════════════════════════════════════════════════════════
-- PARTE 3: REALTIME (Suscripciones en vivo)
-- ═══════════════════════════════════════════════════════════════════════════════

-- Agregar tablas a Realtime (ignora si ya existen)
DO $$ 
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE products;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ 
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE votes;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ 
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE offers;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ 
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE opinions;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ 
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE price_history;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;


-- ═══════════════════════════════════════════════════════════════════════════════
-- PARTE 4: ROW LEVEL SECURITY (RLS)
-- ═══════════════════════════════════════════════════════════════════════════════

-- 4.1 SELLERS
ALTER TABLE sellers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read Sellers" ON sellers;
CREATE POLICY "Public Read Sellers" ON sellers FOR SELECT USING (true);

-- 4.2 PRODUCTS
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read Products" ON products;
DROP POLICY IF EXISTS "Public Update Products" ON products;
CREATE POLICY "Public Read Products" ON products FOR SELECT USING (true);
CREATE POLICY "Public Update Products" ON products FOR UPDATE USING (true);

-- 4.3 VOTES
ALTER TABLE votes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read Votes" ON votes;
DROP POLICY IF EXISTS "Public Insert Votes" ON votes;
CREATE POLICY "Public Read Votes" ON votes FOR SELECT USING (true);
CREATE POLICY "Public Insert Votes" ON votes FOR INSERT WITH CHECK (true);

-- 4.4 OFFERS
ALTER TABLE offers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read Offers" ON offers;
DROP POLICY IF EXISTS "Public Insert Offers" ON offers;
DROP POLICY IF EXISTS "Public Update Offers" ON offers;
CREATE POLICY "Public Read Offers" ON offers FOR SELECT USING (true);
CREATE POLICY "Public Insert Offers" ON offers FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Offers" ON offers FOR UPDATE USING (true);

-- 4.5 OPINIONS
ALTER TABLE opinions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read Opinions" ON opinions;
DROP POLICY IF EXISTS "Public Insert Opinions" ON opinions;
CREATE POLICY "Public Read Opinions" ON opinions FOR SELECT USING (true);
CREATE POLICY "Public Insert Opinions" ON opinions FOR INSERT WITH CHECK (true);

-- 4.6 PRICE_HISTORY
ALTER TABLE price_history ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read Price History" ON price_history;
DROP POLICY IF EXISTS "Public Insert Price History" ON price_history;
CREATE POLICY "Public Read Price History" ON price_history FOR SELECT USING (true);
CREATE POLICY "Public Insert Price History" ON price_history FOR INSERT WITH CHECK (true);


-- ═══════════════════════════════════════════════════════════════════════════════
-- PARTE 5: DATOS DE EJEMPLO (Solo inserta si las tablas están vacías)
-- ═══════════════════════════════════════════════════════════════════════════════

-- 5.1 VENDEDOR DE EJEMPLO
INSERT INTO sellers (id, name, avatar, level, verified)
SELECT 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '@TECH_MASTER_ELITE', 
       'https://api.dicebear.com/7.x/avataaars/svg?seed=Felix', 'NIVEL TECH PREMIUM', true
WHERE NOT EXISTS (SELECT 1 FROM sellers WHERE id = 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11');

-- 5.2 PRODUCTO PRINCIPAL (ID=1)
INSERT INTO products (id, name, description, owner_price, owner_currency, images, video_url, seller_id)
SELECT 1, 
       'Consultoría Estratégica AI (Mensual)', 
       'Servicio premium de optimización de flujos con IA Generativa. Incluye análisis de datos, automatización de procesos y soporte 24/7 para escalar tu negocio.',
       1000, 'USD', 
       ARRAY['https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?auto=format&fit=crop&w=800&q=80', 
             'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80'], 
       '', 
       'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11'
WHERE NOT EXISTS (SELECT 1 FROM products WHERE id = 1);

-- Resetear secuencia si el producto 1 fue insertado manualmente
SELECT setval('products_id_seq', GREATEST((SELECT MAX(id) FROM products), 1));

-- 5.3 VOTOS DE EJEMPLO
INSERT INTO votes (product_id, value, currency, timestamp)
SELECT * FROM (VALUES
    (1::BIGINT, 950::NUMERIC, 'USD', now() - interval '5 days'),
    (1, 1050, 'USD', now() - interval '4 days'),
    (1, 1200, 'USD', now() - interval '3 days'),
    (1, 1100, 'USD', now() - interval '2 days'),
    (1, 3800000, 'COP', now() - interval '1 day'),
    (1, 1300, 'USD', now() - interval '1 hour')
) AS v(product_id, value, currency, timestamp)
WHERE NOT EXISTS (SELECT 1 FROM votes WHERE product_id = 1 LIMIT 1);

-- 5.4 OFERTAS DE EJEMPLO
INSERT INTO offers (product_id, bidder_name, amount, currency, status, created_at)
SELECT * FROM (VALUES
    (1::BIGINT, 'Empresa Tech Global', 1005::NUMERIC, 'USD', 'pending', now() - interval '2 days'),
    (1, 'Agencia Innovación', 3900000, 'COP', 'pending', now() - interval '1 day'),
    (1, 'Startup Ventures', 980, 'USD', 'pending', now() - interval '5 hours')
) AS v(product_id, bidder_name, amount, currency, status, created_at)
WHERE NOT EXISTS (SELECT 1 FROM offers WHERE product_id = 1 LIMIT 1);

-- 5.5 OPINIONES DE EJEMPLO
INSERT INTO opinions (product_id, author_name, content, value, currency, sentiment, created_at)
SELECT * FROM (VALUES
    (1::BIGINT, 'TechReviewer', 'La consultoría estratégica en AI es clave este año.', 5500::NUMERIC, 'USD', 'positive', now() - interval '3 days'),
    (1, 'MarketAnalyst', 'Buen precio base considerando el mercado actual.', 4800, 'USD', 'neutral', now() - interval '2 days'),
    (1, 'InnovationHub', 'El expertis de Tech Master justifica el premium.', 5100, 'USD', 'positive', now() - interval '1 day'),
    (1, 'StartupFounder', 'He visto servicios similares por mucho más.', 5250, 'USD', 'positive', now() - interval '12 hours'),
    (1, 'DataScientist', 'Precio justo para una implementación rápida.', 4950, 'USD', 'neutral', now() - interval '6 hours')
) AS v(product_id, author_name, content, value, currency, sentiment, created_at)
WHERE NOT EXISTS (SELECT 1 FROM opinions WHERE product_id = 1 LIMIT 1);

-- 5.6 HISTORIAL DE PRECIOS DE EJEMPLO
INSERT INTO price_history (product_id, price, currency, created_at)
SELECT * FROM (VALUES
    (1::BIGINT, 800::NUMERIC, 'USD', now() - interval '7 days'),
    (1, 850, 'USD', now() - interval '6 days'),
    (1, 900, 'USD', now() - interval '5 days'),
    (1, 950, 'USD', now() - interval '4 days'),
    (1, 920, 'USD', now() - interval '3 days'),
    (1, 980, 'USD', now() - interval '2 days'),
    (1, 1000, 'USD', now() - interval '1 day'),
    (1, 1000, 'USD', now())
) AS v(product_id, price, currency, created_at)
WHERE NOT EXISTS (SELECT 1 FROM price_history WHERE product_id = 1 LIMIT 1);


-- ═══════════════════════════════════════════════════════════════════════════════
-- PARTE 6: VERIFICACIÓN FINAL
-- ═══════════════════════════════════════════════════════════════════════════════

SELECT '✅ SCRIPT EJECUTADO CORRECTAMENTE!' AS status,
       (SELECT COUNT(*) FROM sellers) AS sellers,
       (SELECT COUNT(*) FROM products) AS products,
       (SELECT COUNT(*) FROM votes) AS votes,
       (SELECT COUNT(*) FROM offers) AS offers,
       (SELECT COUNT(*) FROM opinions) AS opinions,
       (SELECT COUNT(*) FROM price_history) AS price_history;
