-- ==========================================
-- MERCADO SOCIAL - TABLA DE OPINIONES
-- ==========================================
-- Ejecutar en: Supabase SQL Editor
-- NOTA: Ejecuta DESPUÉS de db_setup.sql

-- 1. TABLA: OPINIONES (OPINIONS)
CREATE TABLE IF NOT EXISTS opinions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_name TEXT NOT NULL DEFAULT 'Anónimo',
    content TEXT NOT NULL,
    value NUMERIC NOT NULL,           -- El valor asociado a la opinión
    currency TEXT NOT NULL DEFAULT 'USD',
    sentiment TEXT CHECK (sentiment IN ('positive', 'neutral', 'negative')) DEFAULT 'neutral',
    created_at TIMESTAMPTZ DEFAULT now(),
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE
);

-- 2. HABILITAR REALTIME
ALTER PUBLICATION supabase_realtime ADD TABLE opinions;

-- 3. SEGURIDAD RLS
ALTER TABLE opinions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Opinions" ON opinions FOR SELECT USING (true);
CREATE POLICY "Public Insert Opinions" ON opinions FOR INSERT WITH CHECK (true);

-- 4. DATOS DE EJEMPLO
INSERT INTO opinions (product_id, author_name, content, value, currency, sentiment, created_at) VALUES
    (1, 'TechReviewer', 'La consultoría estratégica en AI es clave este año.', 5500, 'USD', 'positive', now() - interval '3 days'),
    (1, 'MarketAnalyst', 'Buen precio base considerando el mercado actual.', 4800, 'USD', 'neutral', now() - interval '2 days'),
    (1, 'InnovationHub', 'El expertis de Tech Master justifica el premium.', 5100, 'USD', 'positive', now() - interval '1 day'),
    (1, 'StartupFounder', 'He visto servicios similares por mucho más.', 5250, 'USD', 'positive', now() - interval '12 hours'),
    (1, 'DataScientist', 'Precio justo para una implementación rápida.', 4950, 'USD', 'neutral', now() - interval '6 hours'),
    (1, 'ConsultantPro', 'Número redondo para un servicio redondo.', 5000, 'USD', 'neutral', now() - interval '3 hours'),
    (1, 'AIEnthusiast', 'Un poco alto, pero los datos lo respaldan.', 4700, 'USD', 'negative', now() - interval '1 hour'),
    (1, 'FutureTech', 'La IA generativa es el nuevo estándar de oro.', 5400, 'USD', 'positive', now() - interval '30 minutes');
