-- ==========================================
-- MERCADO SOCIAL - HISTORIAL DE PRECIOS
-- ==========================================
-- Ejecutar en: Supabase SQL Editor
-- NOTA: Ejecuta DESPUÉS de db_setup.sql
-- Este script es ADICIONAL y no afecta las tablas existentes

-- 1. TABLA: HISTORIAL DE PRECIOS (PRICE_HISTORY)
CREATE TABLE IF NOT EXISTS price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    price NUMERIC NOT NULL,
    currency TEXT NOT NULL DEFAULT 'USD',
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. HABILITAR REALTIME
ALTER PUBLICATION supabase_realtime ADD TABLE price_history;

-- 3. SEGURIDAD RLS
ALTER TABLE price_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Price History" ON price_history FOR SELECT USING (true);
CREATE POLICY "Public Insert Price History" ON price_history FOR INSERT WITH CHECK (true);

-- 4. ÍNDICE PARA QUERIES RÁPIDAS
CREATE INDEX IF NOT EXISTS idx_price_history_product_date 
ON price_history (product_id, created_at DESC);

-- 5. DATOS INICIALES (Historial ejemplo para el producto 1)
-- Simula cambios de precio en los últimos días
INSERT INTO price_history (product_id, price, currency, created_at) VALUES
    (1, 800, 'USD', now() - interval '7 days'),
    (1, 850, 'USD', now() - interval '6 days'),
    (1, 900, 'USD', now() - interval '5 days'),
    (1, 950, 'USD', now() - interval '4 days'),
    (1, 920, 'USD', now() - interval '3 days'),
    (1, 980, 'USD', now() - interval '2 days'),
    (1, 1000, 'USD', now() - interval '1 day'),
    (1, 1000, 'USD', now()); -- Precio actual
