-- ==========================================
-- MERCADO SOCIAL - SETUP SCRIPT (FULL RESET)
-- ==========================================
-- ADVERTENCIA: Este script reiniciará las tablas relacionadas.
-- Ejecutar en: Supabase SQL Editor

-- 1. LIMPIEZA (Para reiniciar entorno)
DROP TABLE IF EXISTS offers CASCADE;
DROP TABLE IF EXISTS votes CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS sellers CASCADE;

-- 2. TABLA: VENDEDORES (SELLERS)
CREATE TABLE sellers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    avatar TEXT DEFAULT 'https://api.dicebear.com/7.x/avataaars/svg?seed=Default',
    level TEXT DEFAULT 'NIVEL ESTÁNDAR',
    verified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. TABLA: PRODUCTOS (PRODUCTS)
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    owner_price NUMERIC NOT NULL,
    owner_currency TEXT NOT NULL DEFAULT 'USD',
    status TEXT CHECK (status IN ('open', 'locked', 'sold')) DEFAULT 'open',
    final_price NUMERIC,
    final_currency TEXT,
    images TEXT[] DEFAULT '{}',
    video_url TEXT,
    seller_id UUID REFERENCES sellers(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. TABLA: VOTOS (VOTES) - Social Pricing
CREATE TABLE votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value NUMERIC NOT NULL,
    currency TEXT NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT now(),
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE
);

-- 5. TABLA: OFERTAS (OFFERS)
CREATE TABLE offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bidder_name TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    currency TEXT NOT NULL,
    status TEXT CHECK (status IN ('pending', 'accepted', 'rejected')) DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT now(),
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE
);

-- 6. HABILITAR REALTIME (Suscripciones en vivo)
-- Importante: Supabase requiere añadir las tablas a la publicación 'supabase_realtime'
ALTER PUBLICATION supabase_realtime ADD TABLE products;
ALTER PUBLICATION supabase_realtime ADD TABLE votes;
ALTER PUBLICATION supabase_realtime ADD TABLE offers;

-- 7. SEGURIDAD RLS (Row Level Security)
-- Configuración permisiva para DEMO (permite lectura/escritura pública anónima)
-- En producción, esto debe restringirse a usuarios autenticados.

-- Sellers
ALTER TABLE sellers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Sellers" ON sellers FOR SELECT USING (true);

-- Products
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Products" ON products FOR SELECT USING (true);
CREATE POLICY "Public Update Products" ON products FOR UPDATE USING (true); -- Para toggleLock y ventas

-- Votes
ALTER TABLE votes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Votes" ON votes FOR SELECT USING (true);
CREATE POLICY "Public Insert Votes" ON votes FOR INSERT WITH CHECK (true);

-- Offers
ALTER TABLE offers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Offers" ON offers FOR SELECT USING (true);
CREATE POLICY "Public Insert Offers" ON offers FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Offers" ON offers FOR UPDATE USING (true); -- Para aceptar/rechazar

-- ==========================================
-- 8. DATOS DE EJEMPLO (SEED DATA)
-- ==========================================

-- Insertar Vendedor
INSERT INTO sellers (id, name, avatar, level, verified)
VALUES 
    ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '@TECH_MASTER_ELITE', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Felix', 'NIVEL TECH PREMIUM', true);

-- Insertar Producto Principal (ID=1 Obligatorio para la demo por defecto)
INSERT INTO products (id, name, description, owner_price, owner_currency, images, video_url, seller_id)
VALUES 
    (1, 
    'Consultoría Estratégica AI (Mensual)', 
    'Servicio premium de optimización de flujos con IA Generativa. Incluye análisis de datos, automatización de procesos y soporte 24/7 para escalar tu negocio.',
    1000, 
    'USD', 
    ARRAY['https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80'], 
    '', 
    'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11');

-- Resetear secuencia de ID para evitar conflictos futuros
SELECT setval('products_id_seq', (SELECT MAX(id) FROM products));

-- Insertar Votos Históricos (Para generar gráfica inicial)
INSERT INTO votes (product_id, value, currency, timestamp) VALUES
    (1, 950, 'USD', now() - interval '5 days'),
    (1, 1050, 'USD', now() - interval '4 days'),
    (1, 1200, 'USD', now() - interval '3 days'),
    (1, 1100, 'USD', now() - interval '2 days'),
    (1, 3800000, 'COP', now() - interval '1 day'), -- ~$1000 USD
    (1, 1300, 'USD', now() - interval '1 hour');

-- Insertar Ofertas Pendientes
INSERT INTO offers (product_id, bidder_name, amount, currency, status, created_at) VALUES
    (1, 'Empresa Tech Global', 1005, 'USD', 'pending', now() - interval '2 days'),
    (1, 'Agencia Innovación', 3900000, 'COP', 'pending', now() - interval '1 day'),
    (1, 'Startup Ventures', 980, 'USD', 'pending', now() - interval '5 hours');
