/**
 * Script para crear tablas adicionales en Supabase PostgreSQL
 * Ejecutar: node setup-db.mjs
 */

// Configuración de conexión directa a PostgreSQL
const POSTGRES_CONFIG = {
    host: 'constructora-blu-supabase-b8d1d8-68-178-167-234.traefik.me',
    port: 5432,
    database: 'postgres',
    user: 'postgres',
    password: 'pwmxdtlrqokkgqxweifwygfyynmclrd6'
};

// SQL a ejecutar
const SQL_STATEMENTS = [
    // 1. Crear tabla price_history
    `CREATE TABLE IF NOT EXISTS price_history (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
        price NUMERIC NOT NULL,
        currency TEXT NOT NULL DEFAULT 'USD',
        created_at TIMESTAMPTZ DEFAULT now()
    )`,

    // 2. RLS para price_history
    `ALTER TABLE price_history ENABLE ROW LEVEL SECURITY`,

    // 3. Políticas RLS (con DROP IF EXISTS primero)
    `DROP POLICY IF EXISTS "Public Read Price History" ON price_history`,
    `CREATE POLICY "Public Read Price History" ON price_history FOR SELECT USING (true)`,

    `DROP POLICY IF EXISTS "Public Insert Price History" ON price_history`,
    `CREATE POLICY "Public Insert Price History" ON price_history FOR INSERT WITH CHECK (true)`,

    // 4. Índice
    `CREATE INDEX IF NOT EXISTS idx_price_history_product_date ON price_history (product_id, created_at DESC)`,

    // 5. Datos de ejemplo (solo si está vacía)
    `INSERT INTO price_history (product_id, price, currency, created_at)
     SELECT * FROM (VALUES
        (1::BIGINT, 800::NUMERIC, 'USD', now() - interval '7 days'),
        (1, 850, 'USD', now() - interval '6 days'),
        (1, 900, 'USD', now() - interval '5 days'),
        (1, 950, 'USD', now() - interval '4 days'),
        (1, 920, 'USD', now() - interval '3 days'),
        (1, 980, 'USD', now() - interval '2 days'),
        (1, 1000, 'USD', now() - interval '1 day'),
        (1, 1000, 'USD', now())
     ) AS v(product_id, price, currency, created_at)
     WHERE NOT EXISTS (SELECT 1 FROM price_history LIMIT 1)`
];

// Intentar con fetch a la API de Supabase Meta (para DDL)
async function runViaMeta() {
    const SUPABASE_URL = 'http://constructora-blu-supabase-b8d1d8-68-178-167-234.traefik.me';
    const SERVICE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NjkxODkxNTAsImV4cCI6MTg5MzQ1NjAwMCwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlzcyI6InN1cGFiYXNlIn0.K97vEiWdVvBuu0YeBaxqwL1RnnCRfBOdr7r-AJN_zAA';

    // El endpoint /pg/query permite ejecutar SQL (solo en self-hosted con acceso admin)
    const fullSQL = SQL_STATEMENTS.join(';\n');

    console.log('🔄 Intentando ejecutar SQL via Meta API...\n');

    try {
        // Intento 1: pg-meta endpoint
        const response = await fetch(`${SUPABASE_URL}/pg/query`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'apikey': SERVICE_KEY,
                'Authorization': `Bearer ${SERVICE_KEY}`
            },
            body: JSON.stringify({ query: fullSQL })
        });

        if (response.ok) {
            const result = await response.json();
            console.log('✅ SQL ejecutado correctamente!');
            console.log(result);
            return true;
        } else {
            const error = await response.text();
            console.log('❌ Error en pg-meta:', response.status, error);
        }
    } catch (e) {
        console.log('❌ Error de conexión:', e.message);
    }

    return false;
}

// Función principal que muestra instrucciones alternativas
async function main() {
    console.log('═══════════════════════════════════════════════════════════');
    console.log('     MERCADO SOCIAL - Setup de Base de Datos');
    console.log('═══════════════════════════════════════════════════════════\n');

    const success = await runViaMeta();

    if (!success) {
        console.log('\n═══════════════════════════════════════════════════════════');
        console.log('  ALTERNATIVA: Ejecutar SQL directamente en PostgreSQL');
        console.log('═══════════════════════════════════════════════════════════\n');

        console.log('Opción 1: Desde terminal del servidor Dokploy:\n');
        console.log(`   docker exec -i ${POSTGRES_CONFIG.host.split('.')[0]}-db psql -U postgres -d postgres << 'EOF'`);
        console.log(SQL_STATEMENTS.join(';\n'));
        console.log('EOF\n');

        console.log('Opción 2: Copia este SQL y pégalo en el SQL Editor de Supabase Studio:\n');
        console.log('─────────────────────────────────────────────────────────────');
        console.log(SQL_STATEMENTS.join(';\n\n') + ';');
        console.log('─────────────────────────────────────────────────────────────\n');
    }
}

main().catch(console.error);
